dist: trusty
sudo: false

language: node_js
node_js:
  - "10.9.0"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install
  - npm install codecov -g

after_success:
  - codecov

script:
  - npm run test cookie-service -- --no-watch --no-progress --browsers=ChromeHeadless
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
  - npm run build-lib

deploy:
  provider: npm
  email: "owner_mail"
  api_key: "NPM_AUTH_TOKEN"
  local_dir: dist/cookie-service
  on:
  tags: true
  all_branches: true
