dist: trusty
sudo: false

language: node_js
node_js:
  - "10.9.0"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: Test Library
      script:
        - npm run test cookie-service -- --no-watch --no-progress --browsers=ChromeHeadless
    - stage: Npm Release
      node_js: "10.9.0"
      script:
        - echo "Deployig to NPM..."
        - npm run build-lib
        - npm run copy-readme
        - cd dist/cookie-service
      deploy:
        provider: npm
        email: "owner_mail"
        api_key: "NPM_AUTH_TOKEN"
        on:
          tags: true
          all_branches: true
    - stage: Deploy docs
      node_js: "10.9.0"
      script:
        - echo "Deploying to gh Page..."
        - npm run build-docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: dist/cookie-consent
        fqdn: cookie-consent.org
        on:
          tags: true
          branch: master